### ISSUE TITLE
Security vulnerability in ibm-cloud-sdk-core dependency (v3.2.1)

### ISSUE THREAD

**Issue by thakee-kochasoft** [IBM/vpc-node-sdk#28]
[ibm-cloud-sdk-core 3.2.1](https://github.com/IBM/vpc-node-sdk/blob/9b990a059f3d9bf2e1d46a7b5c0e5bce6f078004/package.json#L39) uses JWT 8.5.1 which has a security vulnerability and they have updated the JWT dependency to 9.0 in the last week commit (https://github.com/IBM/node-sdk-core/commit/f0aa9e50c3240c52082068b5a0c0d5c5ea01420b). We should also update the sdk-core dependency to fix this issue.

![Screenshot from 2023-01-04 22-25-13](https://user-images.githubusercontent.com/113889842/210612620-df095b5b-4602-44ef-bb08-8f08a7a3bae4.png)

![Screenshot from 2023-01-04 22-25-44](https://user-images.githubusercontent.com/113889842/210613162-cc654a16-1612-4e5a-8b36-c604e78f97d2.png)

**Comment by SunithaGudisagarIBM1** [comment]
@thakee-kochasoft..   We have updated the version to 4.0.3, "ibm-cloud-sdk-core": "4.0.3".

Thank you
Sunitha
